name: Destroy Infrastructure

on:
  workflow_dispatch

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Terraform State from artifact
      uses: actions/download-artifact@v2
      with:
        name: terraform-state

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init

    - name: Destroy Terraform infrastructure
      run: terraform destroy -auto-approve -state=terraform.tfstate
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}