name: Provision Infrastructure

on: 
  workflow_dispatch 

jobs:
  terraform_provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Save Terraform State
      run: terraform state pull > terraform.tfstate

    - name: Save State as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tfstate
        path: terraform.tfstate